apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres-service

## Deployment should go first
spec:
  selector:
    ## getting from deployment metadata label
    app: postgres
  ports:
    - protocol: TCP
      port: 80
      # deployment file send request to port 8080 and we are listing here at target port
      targetPort: 5432
