apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert
  namespace: istio-system
spec:
  secretName: gamesnews-cert
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: gamesnews.in
  dnsNames:
    - gamesnews.in
