apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule ## Used to break the service into parts
metadata:
  name: nginx-service-dr-2
spec:
  host: nginx-service-2.default.svc.cluster.local
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
