apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: graphql-example
  labels:
    app: postgres

# Service Specification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    # Configuration inside configuration of Pod
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PG_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PG_USERNAME
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-database-storage
              mountPath: /var/lib/postgresql/data ## inside the container where actual data stored is mount to machine physical storage

      volumes:
        - name: postgres-database-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
