apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx

# Service Specification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    # Configuration inside configuration of Pod
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
