apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: okta-backend-service-policy
spec:
  selector:
    matchLabels:
      app: okta-backend
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
