namespace: okta-auth

resources:
  - authConfig.yaml
  - authorization_policy.yaml
  - authSecret.yaml
  - gateway.yaml
  - namespace.yaml
  - okta-backend-deployment.yaml
  - okta-react-config.yaml
  - okta-react-deployment.yaml
  - okta-react-secret.yaml
  - request-auth.yaml
  - virtual-service-mongo.yaml
