apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtual-service-mongo
spec:
  hosts:
    - "*"
  gateways:
    - service-gateway
  http:
    # - match: #match can be removed
    #     - uri:
    #         exact: /mongo
    #   rewrite:
    #     uri: /
    - route:
        - destination:
            port:
              number: 8081
            host: mongo-express-service
