namespace: graphql-example

resources:
  - namespace/namespace.yaml
  - graphql/config.yaml
  - graphql/gateway.yaml
  - graphql/virtual_service-nginx.yaml
  - graphql/service.yaml
  - graphql/deployment.yaml
  - postgress/persistent-volume-claim.yaml
  - postgress/persistent-volume.yaml
  - postgress/secret.yaml
  - postgress/deployment.yaml
  - postgress/service.yaml

---
## PWD should be ./graphQL_application_example
## kubectl apply -k kustomization/
