apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: graphql-virtual-service
  namespace: graphql-example
spec:
  hosts:
    - "*"
  gateways:
    - service-gateway
  http:
    - match:
        - uri:
            exact: /nginx
      rewrite:
        uri: /
      route:
        - destination:
            port:
              number: 9090
            host: graphql-service
