apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    app: hello-world
    service: hello-world
spec:
  ports:
    - port: 5000
      name: http
      targetPort: 5000
  selector:
    app: hello-world
