apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule ## Used to break the service into parts
metadata:
  name: nginx
spec:
  host: nginx
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
    - name: v3
      labels:
        version: v3
