apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  namespace: graphql-example
  labels:
    app: graphql

# Service Specification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql
  template:
    # Configuration inside configuration of Pod
    metadata:
      labels:
        app: graphql
    spec:
      containers:
        - name: graphql
          image: someshdokerbox/graphql-boiler-plate
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: PORT

            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: HOST

            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PG_USERNAME

            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PG_PASSWORD

            - name: PG_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: POSTGRES_DB
