apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: graphql-virtual-service
  namespace: graphql-example
spec:
  hosts:
    - "*"
  gateways:
    - service-gateway
  http:
    - route:
        - destination:
            port:
              number: 8080
            host: graphql-service
